### ISSUE TITLE
Mockup overlay freezes when changing around different mockups and Game view size

### ISSUE THREAD

**Issue by 5argon** [5argon/NotchSolution#10]
Not sure what is going on but to fix it I have to reload the scene..

**Comment by 06Games** [comment]
It seems to be a bug of the editor.
The solution I found to solve this problem is to disable and enable the image component.

For this, I added these 2 lines in the SetMockupSprite function of MockupCanvas.cs after applying the sprite:
```cs
mockupImage.enabled = false;
mockupImage.enabled = true;
```
So yes, it's not very clean but it works...
