### ISSUE TITLE
EditorPrefs are bad

### ISSUE THREAD

**Issue by 5argon** [5argon/NotchSolution#25]
The problem is that they persist to the other project. EditorPrefs are per-Unity client version. In the future I want to add more tools to switch between layouts, working on a portrait project then switch to horizontal project will make the useless settings spill over.

The correct way I think is to use `ScriptableObject` serialized to `ProjectSettings` like everything else so it is truly per-project. (Save-load with `AssetDatabase.LoadAssetAtPath` should be possible since normally I have to type "Assets/" to the path, now we simply change it to "ProjectSettings/" ??)

Then we could ditch the stupid string-as-key and just use declared fields as a proper storage.. it could serialize `Color` without the string gymnastic currently implemented too. lol

**Comment by 06Games** [comment]
I totally agree, the EditorPrefs are not a good solution. 
But isn't it easier to use PlayerPrefs? These are specific to each project and it would be enough to use them only in the editor and voila.

**Comment by 06Games** [comment]
Otherwise, if you want, I can load serialize a class in XML and save it in ProjectSettings

**Comment by 5argon** [comment]
It is now a JSON-based ProjectSettings. Closing this.
