### ISSUE TITLE
Exception on reload

### ISSUE THREAD

**Issue by puschie286** [5argon/NotchSolution#52]
hi, we are getting following error each time unity is started and when scripts are compiled - tested on Unity 2020.1.0b11.3880, Unity 2020.1.0f1
Exception thrown while invoking [DidReloadScripts] method 'E7.NotchSolution.Editor.NotchSimulator:OnScriptsReloaded ()' : NullReferenceException: Object reference not set to an instance of an object
E7.NotchSolution.Editor.NotchSimulator.EnsureCanvasAndEventSetup (UnityEditor.Experimental.SceneManagement.PrefabStage prefabStage) (at Library/PackageCache/com.e7.notch-solution@6f1e6a308e/Editor/Simulator/NotchSimulator.cs:390)
E7.NotchSolution.Editor.NotchSimulator.UpdateAllMockups () (at Library/PackageCache/com.e7.notch-solution@6f1e6a308e/Editor/Simulator/NotchSimulator.cs:291)
E7.NotchSolution.Editor.NotchSimulator.OnScriptsReloaded () (at Library/PackageCache/com.e7.notch-solution@6f1e6a308e/Editor/Simulator/NotchSimulator.cs:269)

**Comment by 5argon** [comment]
Try the latest commit and see if the main feature still works or not please.

**Comment by puschie286** [comment]
the error is fixed - also our art department has confirmed its working.
Thanks for fast response 👍
