### ISSUE TITLE
NotchSolutionUIBehaviourBase.UpdateRect is private protected

### ISSUE THREAD

**Issue by yasirkula** [5argon/NotchSolution#53]
Thank you for the great plugin! I'm planning to write an article about it.

I was trying to write a custom notch script that extends **NotchSolutionUIBehaviourBase** but I realized that it won't compile until I put it inside the `NotchSolution/Runtime` folder (which is harder when Package Manager is used). It's caused by the `private protected abstract void UpdateRect();` method. Would you consider changing its visibility to `protected`?

Here's my custom notch script:

```csharp
using E7.NotchSolution;
using UnityEngine;

public class NotchTest : NotchSolutionUIBehaviourBase
{
	private protected override void UpdateRect()
	{
		Rect safeArea = SafeAreaRelative;
		rectTransform.anchorMin = new Vector2( rectTransform.anchorMin.x, safeArea.yMax );

		m_Tracker.Clear();
		m_Tracker.Add( this, rectTransform, DrivenTransformProperties.AnchorMaxY | DrivenTransformProperties.PivotY );

		rectTransform.anchorMax = new Vector2( rectTransform.anchorMax.x, 1f );
		rectTransform.pivot = new Vector2( rectTransform.pivot.x, 1f );
	}
}
```

It expands the top background with the notch:

![notch](https://user-images.githubusercontent.com/10211608/101278839-29901b00-37cf-11eb-8098-24f0c6eb6ca9.gif)

**Comment by 5argon** [comment]
Thank you for your PR! I had no time for years to maintain this, now I am getting back to it.
